### ISSUE TITLE
Missing body after request server request with: createFromGlobals

### ISSUE THREAD

**Issue by dominikzogg** [slimphp/Slim-Psr7#108] opened 2019-08-01 20:59 UTC
https://github.com/slimphp/Slim-Psr7/blob/master/src/Factory/ServerRequestFactory.php#L93

'php://input' is missing

**Comment by l0gicgate** [comment] 2019-08-01 21:06
Duplicate of #97

**Closed by l0gicgate** 2019-08-01 21:06 UTC
